Add management command to calculate tree locations from CSV
azavea/nyc-trees pull request #1891
Opened 2017-01-18 20:24 UTC by maurizi

This command scans a CSV file of survey data and executes the Treekit geometry construction algorithm to calculate tree locations.
Lat/lng fields are appended to each row of the original CSV.

This builds on top of work done by @kdeloach, and adds the ability to determine which end of the blockface the survey was started at by comparing the distance from the newly provided X/Y points to both the start and ends of the blockface geometry.

I also corrected a bug in the original command: the command was making the `distance_to_tree` field be from the start of the blockface for each tree, but the geometry constructor expects `distance_to_tree` to be the distance from the previous tree (or the start of the blockface) which is conveniently what the spreadsheet provides.

There were a number of duplicate rows in the provided spreadsheet, as well as several rows with no blockface ID. I decided to drop any rows with no Blockface ID, as well as drop any duplicate rows.

This is the input CSV I used (it is the `WITH_XY` sheet of the provided spreadsheet, sorted by Blockface ID and Tree ID).
[2016_11_23_NYC_Parks_Data_for_Treecorder.txt](https://github.com/azavea/nyc-trees/files/714938/2016_11_23_NYC_Parks_Data_for_Treecorder.txt)

This is the output I received.
[output.txt](https://github.com/azavea/nyc-trees/files/714939/output.txt)

I verified my results by manually running through the Treecorder for Blockface `203652`, and verified that the Lat/Lng provided by the Geometry Constructor when used via the UI matched the Lat/Lng provided by this command.

2017-01-18 20:30 UTC, kdeloach commented
:clap: Feel free to squash my WIP commit.

2017-01-19 15:01 UTC, maurizi commented
Waffle

2017-01-19 15:23 UTC, maurizi commented on src/nyc_trees/apps/survey/management/commands/treecorder.py
> +        end_dst = blockface_end.distance(survey_start_point)
Typo: This should be `survey_end_point` here

2017-01-20 19:30 UTC, jwalgran requested changes

2017-01-20 19:30 UTC, jwalgran commented on src/nyc_trees/apps/survey/management/commands/treecorder.py
> +        rows = list(rows)
I see this function being called in one place, with the output of a list comprehension as the `rows` parameter. Is this call to `list` redundant?

2017-01-20 19:30 UTC, jwalgran commented on src/nyc_trees/apps/survey/management/commands/treecorder.py
> +        blockface_end = Point(blockface.geom.coords[0][0], srid=4326)
`blockface_start` and `blockface_end` are being set to `coords[0][0]`, which does not look right. I think `blockface_end` should be to
`coords[length_of_first_dimension-1][length_of_second_dimension-1]`

I used [an online CSV to GeoJSON converter](http://www.convertcsv.com/csv-to-geojson.htm) (flipping the lat and lng columns) and loaded the resulting file into QGIS with the blockface layer and Google satellite imagery.

Here is a screenshot of blockface 225494

<img width="791" alt="screen shot 2017-01-20 at 12 21 58 pm" src="https://cloud.githubusercontent.com/assets/17363/22162439/fa158cf4-df0b-11e6-8465-72a84934b348.png">

This appears to support the idea that the geometries were constructed from the wrong start point.

2017-01-20 19:30 UTC, jwalgran commented on src/nyc_trees/apps/survey/management/commands/treecorder.py
> +                lat, lng = point['coordinates']
The values in the `output.txt` attached to the PR appear to be swapped. I think this needs to be

```python
lng, lat = point['coordinates']

2017-01-20 21:01 UTC, maurizi commented on src/nyc_trees/apps/survey/management/commands/treecorder.py
> +                lat, lng = point['coordinates']
Fixed in  	401beb2

2017-01-20 21:04 UTC, maurizi commented on src/nyc_trees/apps/survey/management/commands/treecorder.py
> +        blockface_end = Point(blockface.geom.coords[0][0], srid=4326)
Doh!

I changed this to be `Point(blockface.geom.coords[0][-1], srid=4326)` (the last point of the first segment) in  401beb2.

I'm not sure what blockfaces (if any) have multiple line segments, but the [`getLatLngs` in `mapUtils.js`](https://github.com/azavea/nyc-trees/blob/develop/src/nyc_trees/js/src/lib/mapUtil.js#L21-L28) always uses the first segment, so I chose to mirror that.

2017-01-20 21:05 UTC, maurizi commented on src/nyc_trees/apps/survey/management/commands/treecorder.py
> +        rows = list(rows)
Not necessary, removed in  	401beb2

2017-01-20 21:09 UTC, maurizi commented
New CSV after the PR fixups were made:
[output.txt](https://github.com/azavea/nyc-trees/files/720508/output.txt)

2017-01-23 17:45 UTC, jwalgran approved these changes
Looks good. I spot checked a few additional blocks comparing my QGIS project with the original xlsx provided by Parks.

2017-01-23 17:45 UTC, jwalgran commented on src/nyc_trees/apps/survey/management/commands/treecorder.py
> +        blockface_end = Point(blockface.geom.coords[0][-1], srid=4326)
Blockface 225494 now looks correct

<img width="980" alt="screen shot 2017-01-23 at 9 54 13 am" src="https://cloud.githubusercontent.com/assets/17363/22213593/fe43140c-e151-11e6-8fb6-4f139793f2f9.png">

and compares visually to the output produced by the treecorder

<img width="927" alt="screen shot 2017-01-23 at 10 28 15 am" src="https://cloud.githubusercontent.com/assets/17363/22215603/39063464-e159-11e6-92c7-cc384f5918d9.png">

2017-01-23 18:34 UTC, merged